### PR TITLE
LRAC-8010 [F] Prevent events when it's in preview mode

### PR DESCRIPTION
**Pull request by fcodias**
https://issues.liferay.com/browse/LRAC-8010

relies on https://github.com/fcodias/liferay-portal/pull/29

### CODE REVIEW

**Comment by fcodias** [comment]
ci:test:sf

**Review by kienD — APPROVED** [review]
LGTM

**Comment by fcodias** [comment]
ci:test:relevant

**Comment by fcodias** [comment]
ci:forward

**Pull request closed without merging**
