### PR TITLE
LRAC-8200 Fix channelId in Identity requests

### PR DESCRIPTION
**Pull request by fcodias**
https://issues.liferay.com/browse/LRAC-8200

### CODE REVIEW

**Comment by fcodias** [comment]
@kienD @marcellustavares

**Comment by fcodias** [comment]
ci:test:sf

**Comment by fcodias** [comment]
ci:test:relevant

**Review by kienD — APPROVED** [review]
LGTM

**Comment by fcodias** [comment]
ci:forward

**Pull request closed without merging**
