### PR TITLE
LPS-84098 Unit tests

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by fcodias** [comment]
ci:test:sf

**Comment by fcodias** [comment]
ci:help

**Comment by fcodias** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by fcodias** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fcodias** [comment]
Pull request submitted to https://github.com/clovisdasilvaneto/liferay-portal/pull/78. [See changes here.](https://github.com/fcodias/liferay-portal/compare/54bd76bef8b5~3...54bd76bef8b5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
