### PR TITLE
LRAC-8038 Lowercase email before hash

### PR DESCRIPTION
**Pull request by fcodias**
https://issues.liferay.com/browse/LRAC-8038

### CODE REVIEW

**Comment by fcodias** [comment]
ci:test:relevant

**Comment by fcodias** [comment]
ci:test:sf

**Review by kienD — APPROVED** [review]
Is there a possibility that `indentity.email` doesn't exist?

If not, LGTM.

**Comment by fcodias** [comment]
> Is there a possibility that `indentity.email` doesn't exist?
> 
> If not, LGTM.

Thanks Kien, not at this moment, we have a check few lines before. :yay:

**Comment by fcodias** [comment]
ci:forward

**Pull request closed without merging**
