### PR TITLE
LRAC-5826 Auto SF

### PR DESCRIPTION
**Pull request by fcodias**

### CODE REVIEW

**Comment by fcodias** [comment]
ci:forward

**Comment by fcodias** [comment]
ci:test:sf

**Comment by shinnlok** [comment]
ci:test:sf

**Comment by shinnlok** [comment]
ci:test:sf

**Comment by fcodias** [comment]
@shinnlok I resent to https://github.com/fcodias/liferay-portal/pull/21 to check if deleting the AutoSF fix the problem, and it was ok, so I will try forward from there.

cc @andreldm

**Pull request closed without merging**
