### PR TITLE
LPS-100791 Send CTA clicked event

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by fcodias** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fcodias** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78406. [See changes here.](https://github.com/fcodias/liferay-portal/compare/9fad35f025fb~3...9fad35f025fb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fcodias** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78408. [See changes here.](https://github.com/fcodias/liferay-portal/compare/a6995fd84ed2~3...a6995fd84ed2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fcodias** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78411. [See changes here.](https://github.com/fcodias/liferay-portal/compare/07b455396896~3...07b455396896) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by andreldm** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
