### PR TITLE
LPS-128918 Migrate v2 usages in analytics/analytics-settings-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**
- Connect your DXP instance to Analytics Cloud
- Managing analytics data should work as expected

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hi @fcodias did you have the chance to review this change?

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by jbalsas** [comment]
Going to forward this one on our own since the changes are pretty trivial and tests are green. We've been doing the same with other teams to alleviate the workload and make sure this makes it in time for the stabilization period. We can follow up on it if anything is wrong.

Thanks! 🤗

**Comment by jbalsas** [comment]
ci:forward

**Comment by julien** [comment]
Thanks @jbalsas

**Comment by fcodias** [comment]
Thanks @julien and @jbalsas

**Pull request closed without merging**
